application: google.com:scuttlebutt
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /dispatch
  script: task_handler.py
  login: admin
  
- url: /download
  script: task_handler.py
  login: admin
  
- url: /report/.*
  script: report_handler.py