application: google.com:scuttlebutt
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /admin/.*
  script: web_ui.py
  login: admin

- url: /helloworld
  script: helloworld.py

- url: /update_news_topics
  script: update_news_topics_handler.py
  login: admin
